options(download.file.method="curl")
install.packages("devtools", repos="https://cran.rstudio.com")
library(devtools)
install_version("binman", version = "0.1.0", repos = "https://cran.rstudio.com")
install_version("wdman", version = "0.2.2", repos = "https://cran.rstudio.com")
install_version("RSelenium", version = "1.7.1", repos = "https://cran.rstudio.com")
pJS <- RSelenium::phantom()
pJS$stop()
