#!/bin/bash
set -x
set -e

free -m

DIR=/vagrant

PACKAGE=$1

bash $DIR/packages/$PACKAGE/install

if [ -f $DIR/packages/$PACKAGE/test.R ]; then
    sudo R -f $DIR/packages/$PACKAGE/test.R
else
    sudo R -e "install.packages('$PACKAGE', repos='http://cran.rstudio.com/'); library('$PACKAGE')"
fi

exit $?
