#!/bin/bash
set -x
set -e

free -m

DIR=/vagrant

PACKAGE=$1

bash $DIR/packages/$PACKAGE/install

sudo R -e "install.packages('$PACKAGE', repos='http://cran.rstudio.com/'); library('$PACKAGE')"

exit $?
