---
name: 'Shinyapps Package Dependency Tests'
description: 'Runs all supplied tests of R package dependency installers'

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
    pull_request:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

runs:
  using: 'docker'
  image: 'docker://rstudio/shinyapps-package-dependencies:focal'

jobs:
  list-tests:
    steps:
      - name: List Tests
        id: list-tests
        run: echo '::set-output name=matrix::["rsvg"]'
  
