---
name: 'Shinyapps Package Dependency Tests'

on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/**'
      - '.github/workflows/*.yml'

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  list-tests:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.list-tests.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - name: List Tests
        id: list-tests
        run: echo "::set-output name=matrix::$(ls -1 -d packages/* | grep -v gsl | tr '\n' '\0' | xargs -0 -n 1 basename | jq -Rsc '. / "\n" - [""]')"

  test-package:
    name: ${{ matrix.stack }}
    needs: list-tests
    runs-on: ubuntu-latest
    container:
      image: rstudio/shinyapps-package-dependencies:focal
    strategy:
      matrix: ${{fromJSON(needs.list-tests.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v3
      - run: make test-focal-${{ matrix.stack }}
