on:
  push:
    branches:
      - main
      - master
      - ghactions
      - pak
  pull_request:
    branches:
      - main
      - master
  # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onschedule
  # schedule:
  #   - cron:  '0 0 * * 1' # every monday at midnight

name: Test packages

jobs:
  packages:
    runs-on: ubuntu-latest
    outputs:
      pkgs: ${{ steps.set_pkgs.outputs.pkgs }}
    steps:
    - uses: actions/checkout@v2
    - id: set_pkgs
      # https://stackoverflow.com/a/32354503/591574
      run: |
        PKGS=`ls packages | jq -R '[.]' | jq -s -c 'add'`
        echo "::set-output name=pkgs::{\"name\":$PKGS}"
    - name: debug
      run: |
        echo "${{ steps.set_pkgs.outputs.pkgs }}"

  test:
    runs-on: ubuntu-latest

    name: ${{ matrix.docker_type }} - ${{ matrix.pkg }}

    strategy:
      fail-fast: false

      # Test using independent docker images
      # Isolated testing so that a prior package doesn't "help" another package
      matrix:
        # dynamic pkg names from the `./packages` folder
        # https://github.blog/changelog/2020-04-15-github-actions-new-workflow-features/
        pkg: ${{ fromJson(needs.packages.outputs.pkgs) }}
        docker_type:
        - bonic
        - xenial

    steps:
      - uses: actions/checkout@v2

      - name: Build local docker file
        run: |
          make docker-build-${{ matrix.docker_type }}

      - name: "Test package: ${{ matrix.pkg.name }}"
        run: |
          make test-${{ matrix.docker_type }}-${{ matrix.pkg.name }}
